name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  branch-prefix:
    description: 'Branch prefix e.g. "rhino-" if your branches look like "rhino-1.x"'
    default: ''
runs:
  using: 'node20'
  main: 'index.js'
